### PR TITLE
Connection State Machine and StateHandler

### PR DESCRIPTION
**Pull request by btoms20**
## Purpose
Preliminary support for a Connection State Machine and a `StateHandler` that unifies the previously separate `ServerHandler` and `ClientHandler`.

> **Note**
> The general QUIC Connection State Machine discussion has outlived this PR and now resides [here](https://github.com/swift-quic/swift-quic/discussions/15). Please direct any comments, concerns, issues, ideas you may have regarding the Connection State Machine to the [discussion page](https://github.com/swift-quic/swift-quic/discussions/15).

This PR introduces the following....

### Responsibilities
- Bridges the `ConnectionStateMachine` and the NIO Pipeline
- Feeds inbound / outbound data through the `ConnectionStateMachine`
- Handles events emitted from the `ConnectionStateMachine`

### Responsibilities
- Provides a single, ground truth, source for the Connection's current state.
- Ensures that the connection can only flow through a very structured route of strictly defined states.
> **Note**
> For more information on how the ConnectionStateMachine is structured check out the [discussion here](#15)

### Idle Connection Timeouts 
- Just a simple Scheduled Task at the moment but helps prevent indefinite hangs during tests.

### A "Time" Based BackToBackEmbeddedChannel 
- Helps yield to NIOSSL during key generations while testing within EmbeddedChannels

### Key Updates via #13 
- Merged from `dev` and integrated into `StateHandler`

### Version Negotiations via #14 
- Merged from `dev` and integrated into `StateHandler`

### CODE REVIEW

**Comment by btoms20** [comment]
I've created a dedicated [discussion](#15) for the `ConnectionStateMachine` instead of using this PR. This way we can move forward with dev work while we continue to hash out / refine the Connection State Machine's design.

**Comment by btoms20** [comment]
With the new branch protection rules in place, requiring all commits to be signed, I tried to retroactively amend each commit  with a signature, but no luck. I'm going to close this PR and open a new one in it's place.

**Comment by kennethlaskoski** [comment]
> With the new branch protection rules in place, requiring all commits to be signed, I tried to retroactively amend each commit with a signature, but no luck. I'm going to close this PR and open a new one in it's place.

Hi, sorry for the inconvenience. I think signed commits are a good thing, we're writing network code after all and security must not be overlooked. Now for the record, as repository owner you can actually bypass such requirements.

**Review by kennethlaskoski — COMMENTED** [review]
PR closed for bureaucratic reasons.

**Pull request closed without merging**
